SERVER_URL = ""
USERNAME = ""
PASSWORD = ""

# Use either the *_ID or directly the named one
# The named one will automaticly detect the *_ID

MOVIES_ID = ""
SERIES_ID = ""

# Or

MOVIES = ""
SERIES = ""

SUBTITLES_OUTPUT = ''
SUBTITLES_TMP = '/tmp/jellyfin2txt'

# The proxy url to deserve the subtiles, full http url usable where the subtitles are in one big folder.
# End slash not needed
PROXY_URL = "http://myhost.example.com/subtitles"